# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('netflixdb', '0004_auto_20171010_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='id',
        ),
        migrations.RemoveField(
            model_name='details',
            name='id',
        ),
        migrations.RemoveField(
            model_name='director',
            name='id',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='id',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='name',
            name='id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='contact_id',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='pname_id',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='id',
        ),
        migrations.RemoveField(
            model_name='release',
            name='id',
        ),
        migrations.RemoveField(
            model_name='soap',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='personal',
            name='name_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='netflixdb.Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='details',
            name='details_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='details',
            name='personal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixdb.Personal'),
        ),
        migrations.AlterField(
            model_name='director',
            name='director_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='genre_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixdb.Director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixdb.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixdb.Release'),
        ),
        migrations.AlterField(
            model_name='name',
            name='name_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personal',
            name='personal_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixdb.Payment'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='release',
            name='release_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soap',
            name='director_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixdb.Director'),
        ),
        migrations.AlterField(
            model_name='soap',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixdb.Genre'),
        ),
        migrations.AlterField(
            model_name='soap',
            name='release_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixdb.Release'),
        ),
        migrations.AlterField(
            model_name='soap',
            name='soap_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='details_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixdb.Details'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixdb.Location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netflixdb.Plan'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
